spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306
    name: survey
    password: root
  servlet:
     multipart:
      enabled: 'true'
      max-file-size: 200MB
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: none
  flyway:
    user: root
    password: root
    url: jdbc:mysql://localhost:3306
    schemas : survey
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true


server:
  servlet:
    context-path:
  port: 8080
  
management:
    endpoints:
      web:
        exposure:
          include: '*'
        base-path: '/manage'
    server:
         port: 8081 
    