CREATE TABLE SURVEY_RESPONSE (
SURVEY_ID INT,
RESPONSE_ID INT,
PRIMARY KEY (SURVEY_ID, RESPONSE_ID),
FOREIGN KEY (SURVEY_ID) REFERENCES SURVEY(SURVEY_ID),
FOREIGN KEY (RESPONSE_ID) REFERENCES RESPONSE(RESPONSE_ID)
);