CREATE TABLE RESPONSE (
RESPONSE_ID INT,
QUESTION_ID INT,
ANSWER_ID INT,
PRIMARY KEY (RESPONSE_ID, QUESTION_ID, ANSWER_ID),
FOREIGN KEY (QUESTION_ID) REFERENCES QUESTION(QUESTION_ID),
FOREIGN KEY (ANSWER_ID) REFERENCES ANSWER(ANSWER_ID)
);